/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.punchcafe.sefizzbuzz.cli.process;

import dev.punchcafe.sefizzbuzz.cli.client.FavouritePayload;
import dev.punchcafe.sefizzbuzz.cli.client.FizzBuzzClient;
import dev.punchcafe.sefizzbuzz.cli.client.FizzBuzzEntity;
import dev.punchcafe.sefizzbuzz.cli.config.AppConfig;
import dev.punchcafe.sefizzbuzz.cli.config.AppFactory;
import dev.punchcafe.sefizzbuzz.cli.exception.ArgumentNeededException;
import dev.punchcafe.sefizzbuzz.cli.exception.MissingCommandException;
import dev.punchcafe.sefizzbuzz.cli.exception.UnknownArgumentException;
import dev.punchcafe.sefizzbuzz.cli.io.UserInputReader;
import dev.punchcafe.sefizzbuzz.cli.io.UserOutputWriter;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import java.util.List;
import java.util.Scanner;

import static dev.punchcafe.sefizzbuzz.cli.constant.MessageConstants.HELP_MESSAGE;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.*;

class FavouriteTest {

    private FizzBuzzClient fizzBuzzClient;
    private UserOutputWriter userOutputWriter;
    private UserInputReader userInputReader;
    private Scanner inputScanner;
    private AppProcess appProcess;

    @BeforeEach
    void beforeEach() {
        inputScanner = Mockito.mock(Scanner.class);
        userOutputWriter = Mockito.spy(new UserOutputWriter(System.out));
        userInputReader = new UserInputReader(inputScanner);
        fizzBuzzClient = Mockito.mock(FizzBuzzClient.class);
        final var appConfig = AppConfig.builder()
                .userOutputWriter(userOutputWriter)
                .userInputReader(userInputReader)
                .fizzBuzzClient(fizzBuzzClient)
                .build();
        appProcess = new AppFactory(appConfig).buildApp();
    }

    @Test
    void userCanFavouriteFizzBuzz() {
        when(fizzBuzzClient.updateFavourite(eq(15), eq(FavouritePayload.buildFrom(true))))
                .thenReturn(new FizzBuzzEntity(15, "FizzBuzz", true));
        appProcess.execute(List.of("favourite", "15"));
        verify(fizzBuzzClient, times(1)).updateFavourite(15, FavouritePayload.buildFrom(true));
        verify(userOutputWriter, times(1))
                .printToUser("Result:  id: 15,  value: FizzBuzz");
    }

    @Test
    void userCanUnfavouriteFizzBuzz() {
        when(fizzBuzzClient.updateFavourite(eq(15), eq(FavouritePayload.buildFrom(false))))
                .thenReturn(new FizzBuzzEntity(15, "FizzBuzz", false));
        appProcess.execute(List.of("unfavourite", "15"));
        verify(fizzBuzzClient, times(1)).updateFavourite(15, FavouritePayload.buildFrom(false));
        verify(userOutputWriter, times(1))
                .printToUser("Result:  id: 15,  value: FizzBuzz");
    }

    @Test
    void appThrowsExceptionIfUserHasntProvidedFizzBuzzIdOnFavourite() {
        assertThrows(ArgumentNeededException.class, () -> appProcess.execute(List.of("favourite")));
    }

    @Test
    void appThrowsExceptionIfUserHasntProvidedFizzBuzzIdOnUnfavourite() {
        assertThrows(ArgumentNeededException.class, () -> appProcess.execute(List.of("unfavourite")));
    }

    @Test
    void appThrowsExceptionIfUserProvidesExtraArgsOnFavourite() {
        assertThrows(UnknownArgumentException.class, () -> appProcess.execute(List.of("favourite", "10", "hello")));
    }

    @Test
    void appThrowsExceptionIfUserProvidesExtraArgsOnUnfavourite() {
        assertThrows(UnknownArgumentException.class, () -> appProcess.execute(List.of("unfavourite", "10", "hello")));
    }
}
